apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-metrics
spec:
  schedule: "0 * * * *"  
  jobTemplate:             
    spec:
      template:       
        spec:
          containers:
          - name: batch-metrics
            image: perl
            command: ["curl",  "http://metrics-ipaas-bots.b6ff.rh-idev.openshiftapps.com/batch?async=true"]
          restartPolicy: OnFailure 
